import { Router } from "express";
import authRouter from "./auth.route";
import userRouter from "./user.route";
import adminRouter from "./admin.route";
import dashboardRouter from "./dashboard.route";
import hubRouter from "./hub.route";
import r2Router from "./r2.route";
import billingRouter from "./billing.route";
import testerRouter from "./tester.route";
import blogRouter from "./blog.route";
import reviewRouter from "./review.route";
import supportRouter from "./support.route";
import adminFinanceRouter from "./adminFinance.route";
import declarationRouter from "./declaration.route";
import faqRouter from "./faq.route";
import guideRouter from "./guide.route";
import subscriptionRouter from "./subscription.route";
import mailRouter from "./mail.route";
import appChatRouter from "./appChat.route";

const router = Router();

router.use("/auth", authRouter);
router.use("/user", userRouter);
router.use("/admin/mail", mailRouter);
router.use("/admin", adminRouter);
router.use("/dashboard", dashboardRouter);
router.use("/hub", hubRouter);
router.use("/R2", r2Router);
router.use("/billing", billingRouter);
router.use("/tester", testerRouter);
router.use("/blog", blogRouter);
router.use("/review", reviewRouter);
router.use("/support", supportRouter);
router.use("/admin/finance", adminFinanceRouter);
router.use("/declaration", declarationRouter);
router.use("/faq", faqRouter);
router.use("/blog", guideRouter);
router.use("/subscription", subscriptionRouter);
router.use("/app-chat", appChatRouter);

export default router;
