-- CreateTable
CREATE TABLE "play_store_declaration" (
    "id" SERIAL NOT NULL,
    "dashboardAndHubId" INTEGER NOT NULL,
    "appOwnerId" TEXT NOT NULL,
    "answers" JSONB NOT NULL DEFAULT '{}',
    "autoGeneratedData" JSONB NOT NULL DEFAULT '{}',
    "status" TEXT NOT NULL DEFAULT 'DRAFT',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "play_store_declaration_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "play_store_declaration_dashboardAndHubId_key" ON "play_store_declaration"("dashboardAndHubId");

-- AddForeignKey
ALTER TABLE "play_store_declaration" ADD CONSTRAINT "play_store_declaration_dashboardAndHubId_fkey" FOREIGN KEY ("dashboardAndHubId") REFERENCES "dashboard_and_hub"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "play_store_declaration" ADD CONSTRAINT "play_store_declaration_appOwnerId_fkey" FOREIGN KEY ("appOwnerId") REFERENCES "user"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
