import type { Request, Response } from "express";
import { prismaClient } from "@/lib/prisma";
import { sendSuccess, sendError } from "@/utils/response";

function serialize(obj: unknown) {
  return JSON.parse(JSON.stringify(obj));
}

export async function getDeclaration(req: Request, res: Response) {
  try {
    const appId = req.params.appId as string;
    const userId = req.userId;
    if (!userId) return sendError(res, 401, "Unauthorized");

    const appIdNum = parseInt(appId);
    if (isNaN(appIdNum)) return sendError(res, 400, "Invalid app ID");

    const dashboardAndHub = await prismaClient.dashboardAndHub.findUnique({
      where: { id: appIdNum },
      select: { id: true, appOwnerId: true, status: true },
    });

    if (!dashboardAndHub) return sendError(res, 404, "App not found");
    if (dashboardAndHub.appOwnerId !== userId)
      return sendError(res, 403, "Forbidden");

    if (dashboardAndHub.status !== "COMPLETED") {
      return sendError(
        res,
        400,
        "Declaration is only available for completed tests",
      );
    }

    const existing = await prismaClient.playStoreDeclaration.findUnique({
      where: { dashboardAndHubId: appIdNum },
    });

    if (existing) {
      return sendSuccess(
        res,
        serialize(existing) as any,
        "Declaration fetched successfully",
      );
    }

    const fullData = await prismaClient.dashboardAndHub.findUnique({
      where: { id: appIdNum },
      include: {
        androidApp: {
          include: {
            appCategory: true,
            ratings: { select: { rating: true } },
          },
        },
        feedback: {
          select: { message: true, type: true },
        },
        testerRelations: {
          select: {
            status: true,
            daysCompleted: true,
          },
        },
      },
    });

    if (!fullData) return sendError(res, 404, "App details not found");

    const bugs = fullData.feedback.filter((f) => f.type === "BUG").length;
    const suggestions = fullData.feedback.filter(
      (f) => f.type === "SUGGESTION",
    ).length;
    const praise = fullData.feedback.filter((f) => f.type === "PRAISE").length;

    const autoGeneratedData = {
      totalTesters: fullData.totalTester,
      completedTesters: fullData.testerRelations.filter(
        (tr) => tr.status === "COMPLETED",
      ).length,
      totalDays: fullData.totalDay,
      currentDay: fullData.currentDay,
      bugs,
      suggestions,
      praise,
      totalFeedback: fullData.feedback.length,
      totalRatings: fullData.androidApp?.ratings.length || 0,
      avgRating:
        fullData.androidApp?.ratings.length > 0
          ? Number(
              (
                fullData.androidApp.ratings.reduce(
                  (a: number, r: { rating: number }) => a + r.rating,
                  0,
                ) / fullData.androidApp.ratings.length
              ).toFixed(1),
            )
          : null,
      appType: fullData.appType,
      hasCriticalBugs: false,
      testingStartDate: fullData.testingStartDate,
      testingEndDate: fullData.testingEndDate,
      packageName: fullData.androidApp?.packageName || "",
      category: fullData.androidApp?.appCategory?.name || "",
    };

    const emptyAnswers = {
      recruitmentMethod: "",
      recruitmentEase: "",
      testerEngagement: "",
      feedbackSummary: "",
      feedbackCollectionMethod: "",
      intendedAudience: "",
      valueDescription: "",
      expectedInstalls: "",
      changesMade: "",
      readinessRationale: "",
      customQuestions: [] as any[],
    };

    const declaration = await prismaClient.playStoreDeclaration.create({
      data: {
        dashboardAndHubId: appIdNum,
        appOwnerId: userId,
        answers: emptyAnswers as any,
        autoGeneratedData: autoGeneratedData as any,
        status: "DRAFT",
      },
    });

    return sendSuccess(
      res,
      serialize(declaration) as any,
      "Declaration created successfully",
    );
  } catch (error) {
    console.error("Error in getDeclaration:", error);
    return sendError(res, 500, "Internal server error");
  }
}

export async function updateDeclaration(req: Request, res: Response) {
  try {
    const appId = req.params.appId as string;
    const userId = req.userId;
    if (!userId) return sendError(res, 401, "Unauthorized");

    const appIdNum = parseInt(appId);
    if (isNaN(appIdNum)) return sendError(res, 400, "Invalid app ID");

    const dashboardAndHub = await prismaClient.dashboardAndHub.findUnique({
      where: { id: appIdNum },
      select: { id: true, appOwnerId: true, status: true },
    });

    if (!dashboardAndHub) return sendError(res, 404, "App not found");
    if (dashboardAndHub.appOwnerId !== userId)
      return sendError(res, 403, "Forbidden");

    const answers = req.body.answers;

    const declaration = await prismaClient.playStoreDeclaration.upsert({
      where: { dashboardAndHubId: appIdNum },
      update: {
        answers: answers ? (answers as any) : undefined,
      },
      create: {
        dashboardAndHubId: appIdNum,
        appOwnerId: userId,
        answers: (answers || {}) as any,
        autoGeneratedData: {} as any,
        status: "DRAFT",
      },
    });

    return sendSuccess(
      res,
      serialize(declaration) as any,
      "Declaration updated successfully",
    );
  } catch (error) {
    console.error("Error in updateDeclaration:", error);
    return sendError(res, 500, "Internal server error");
  }
}
